[package]
name = "kak-session-name"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8", features = ["std_rng"] }
